///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Rx_Git_Proj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Rx_Git_ProjRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b497b73b-bbf2-43de-9e36-c75321a1470b")]
    public partial class Rx_Git_ProjRepository : RepoGenBaseFolder
    {
        static Rx_Git_ProjRepository instance = new Rx_Git_ProjRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Rx_Git_ProjRepository element repository.
        /// </summary>
        [RepositoryFolder("b497b73b-bbf2-43de-9e36-c75321a1470b")]
        public static Rx_Git_ProjRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Rx_Git_ProjRepository() 
            : base("Rx_Git_ProjRepository", "/", null, 0, false, "b497b73b-bbf2-43de-9e36-c75321a1470b", ".\\RepositoryImages\\Rx_Git_ProjRepositoryb497b73b.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b497b73b-bbf2-43de-9e36-c75321a1470b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Rx_Git_ProjRepositoryFolders
    {
    }
#pragma warning restore 0436
}
