///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Git_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Git_DemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("afa9bebc-61dd-4a43-b0b5-6435c6ee0d1e")]
    public partial class Git_DemoRepository : RepoGenBaseFolder
    {
        static Git_DemoRepository instance = new Git_DemoRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Git_DemoRepository element repository.
        /// </summary>
        [RepositoryFolder("afa9bebc-61dd-4a43-b0b5-6435c6ee0d1e")]
        public static Git_DemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Git_DemoRepository() 
            : base("Git_DemoRepository", "/", null, 0, false, "afa9bebc-61dd-4a43-b0b5-6435c6ee0d1e", ".\\RepositoryImages\\Git_DemoRepositoryafa9bebc.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("afa9bebc-61dd-4a43-b0b5-6435c6ee0d1e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Git_DemoRepositoryFolders
    {
    }
#pragma warning restore 0436
}
